### ISSUE TITLE
Issues presumably with WKWebView

### ISSUE THREAD

**Issue by NorthMcCormick** [johanblomgren/cordova-plugin-indexappcontent#13]
Hello,

I'm stoked to use this but I am encountering an issue that I think has to do with WKWebView which a lot of cordova devs are moving into. 

I'm getting `-[WKWebView stringByEvaluatingJavaScriptFromString:]: unrecognized selector sent to instance 0x7fa6a9810200
`

I'm able to edit the code a bit to get it to try and execute the javascript function but it never actually executes. I'm not super proficient in the native side, so I'm not sure what else to try. 

Can anyone else take a look and see what they can do to make it compatible maybe?

**Comment by johanblomgren** [comment]
Hi there @NorthMcCormick, I'm happy you're seeing the potential use of this plugin =)

Your assumptions are totally correct - the plugin is written before there was a decent support for `WKWebView` and thus it only support the previously standard `UIWebView`. The error that you are seeing are implying exactly that, as the `WKWebView` interface has changed from the synchronous javascript execution method `stringByEvaluatingJavaScriptFromString` of `UIWebView` to the asynchronous method `evaluateJavaScript:completionHandler:`.

A rudimentary change adding support for `WKWebView` would be to simply check the webview class and use appropriate method. Though one would need to make sure that the plugin is not relying on any return values returned by the synchronous javascript execution. Otherwise the plugin may need to be re-designed with asynchronous flows in mind.

I'll see if I'll manage to find time fixing a somewhat decent solution for this.

**Comment by NorthMcCormick** [comment]
That would be awesome, I took a few hours to poke around and try and make that work but I couldn't seem to get it. Not too keen on the native side haha.

I appreciate the response, if I can help test let me know!

**Comment by johanblomgren** [comment]
@NorthMcCormick If you want to, you can take a quick look at the branch https://github.com/johanblomgren/cordova-plugin-indexappcontent/tree/wkwebview-support. I do however have my doubts about some details in that implementation, but it's worth a try!

**Comment by NorthMcCormick** [comment]
I'll give it a shot later this week and report back, thanks!

**Comment by MarcoEidinger** [comment]
Hi, I posted another pull request to solve that. @johanblomgren would be great if you can review it. Thanks

**Comment by MarcoEidinger** [comment]
Should be fixed with my pull request. You can pull from master directly. However, there will be also a new version  (> v0.1.0) which will contain the fix and some things more
