### ISSUE TITLE
Conflicts with Universal Links plugin

### ISSUE THREAD

**Issue by pitAlex** [johanblomgren/cordova-plugin-indexappcontent#15]
Hi,
I have my ios app setup to use [universal links](https://github.com/nordnet/cordova-universal-links-plugin) plugin and recently I wanted to add the app indexing plugin. The problem is that whenever this plugin is installed the universal links event stops firing. The app still gets opened when pressing a link but no event is triggered.

**Comment by MarcoEidinger** [comment]
Can you share your code or more details so I can have a look?

**Comment by pitAlex** [comment]
Just create an app that uses both plugins, no special settings required. I don't have a code to share anymore because I decided not to use the plugin.

**Comment by MarcoEidinger** [comment]
Sorry to hear that. I will try to have a look in the next 3 weeks

**Comment by MarcoEidinger** [comment]
Found the root cause. Both plugins do something wrong. They don't handle the case that the same function might be implemented by different categories (i.e. plugins) for same class. So the last installed plugin gets called and only this plugin.

In next release of cordova-plugin-indexappcontent we will ensure to call other implementations (e.g universal link plugin) in case user activity is not related to spotlight.

However, also the universal link plugin would have to change it's coding to ensure that our plugin gets called if required

**Comment by MarcoEidinger** [comment]
Alternatively, on native side you can create a subclass of AppDelegate and override application:continueUserActivity:restorationHandler: and in your overridden method you decide which category method to call (either universal links or indexappcontent).

**Comment by MarcoEidinger** [comment]
With version 0.5.0 cordova-plugin-indexappcontent will call other implementation of application:continueUserActivity:restorationHandler if available.
