### ISSUE TITLE
Init breaks js execution

### ISSUE THREAD

**Issue by hessius** [johanblomgren/cordova-plugin-indexappcontent#2]
Hi!
Thanks for updating with examples.
I've used your examples to test a dummy implementation:

```
function onDeviceReady() {
    console.log('Device ready);
    var items = [{
        domain: 'com.pillerkollen.drugname',
        identifier: 'NPLID01',
        title: 'Alvedon',
        description: 'Paracetamol',
        keywords: ['Paracetamol'],
        url: 'http://pk.se/images/logo_dark.png',
    }, {
        domain: 'com.pillerkollen.drugname',
        identifier: 'NPLID02',
        title: 'Bisoprolol actavis',
        description: 'Bisoprolol',
        keywords: ['bisoprolol'],
        url: 'http://pk.se/images/logo_dark.png',
    }];
    window.plugins.indexAppContent.init();
    window.plugins.indexAppContent.setItems(items, function() {
        console.log('Successfully set items');
    }, function(error) {
        console.log('Error: ' + error);
    });
}
```

Maybe I'm missing something but as soon as I pass the init call that breaks the rest of the js execution.
Tried with and without success and error callbacks, the xcode terminal output doesn't output anything after the plugins loaded msgs - not even the "console ready" output. Tried to un- and reinstall the plugin with the same results.
Initially thought it was due to MobileCoreServices.framework not being added during installation but manually adding it didn't change anything.

I'm on cordova cli 6.0.0, cordova iOS 4.0.1, tested on device and simulator

**Comment by johanblomgren** [comment]
@hessius The issue is caused by Cordova adding another _cordova.define_ wrapper around the plugin javascript. The plugin is designed for being loaded from a remote source and thus need the _cordova.define_ statement.

Remove the "cordova.define("cordova-plugin-indexappcontent", function(require, exports, module) {....}" wrapper function and it should work fine.

Please let me know how it works out for you! I was able to get an example project running using the code you supplied.

**Comment by johanblomgren** [comment]
Pull request #3 should resolve the issue.

**Comment by johanblomgren** [comment]
Pull request #4 resolves another issue where the plugin path was wrong.
